---
version: '2'
services:
  this-image:
    restart: 'no'
    build:
      context: ./
      args:
        PYTHON_PKG: ${PYTHON_PKG}
    image: ${DOCKER_ID}/${NAME}:${TAG}
    # for test
    command: /bin/sh -c 'while true; do echo dummy; sleep 600; done'
